services:
  fotokarten:
    build: .
    container_name: fotokarten
    restart: unless-stopped
    ports:
      - "8098:5000"
    volumes:
      - /volume1/PhoneMirror/stefan/gis/geoparquet:/data/geoparquet:ro
      - /volume1/PhoneMirror/stefan/fotos/DCIM:/data/photos:ro
    environment:
      - SOURCE_ROOT=\\DS923Plus\PhoneMirror\stefan\fotos\DCIM
      - PHOTOS_ROOT=/data/photos
